/* AUTO-GENERATED by build/generate.js from build/data.js — do not edit by hand. */
window.HARGROVE_KB = {
  "biz": {
    "name": "Hargrove & Sons",
    "legal": "Hargrove & Sons Plumbing, Inc.",
    "phone": "(562) 431-1960",
    "tel": "+15624311960",
    "license": "C-36 #784512",
    "since": 1992,
    "rating": "4.9",
    "reviews": "2,184",
    "hours": "24/7 emergency service",
    "area": "Greater Sacramento",
    "warranty": "two-year warranty"
  },
  "services": [
    {
      "slug": "emergency-plumbing",
      "title": "Emergency leaks & burst pipes",
      "short": "Burst lines, slab leaks, failed shutoffs, flooding, answered day or night.",
      "body": "Water where it shouldn’t be doesn’t keep business hours, and neither do we. A stocked truck rolls out for burst supply lines, slab leaks, failed shutoff valves, and active flooding, with an average arrival under an hour across the metro.",
      "bullets": [
        "24/7 live phone answer",
        "Average arrival under 60 minutes",
        "Water shutoff & damage control first",
        "Flat-rate quote before the real work starts"
      ]
    },
    {
      "slug": "drain-sewer",
      "title": "Drain & sewer",
      "short": "Camera inspection, hydro-jetting, root removal, trenchless repair.",
      "body": "Older trees and clay sewer lines are a Sacramento specialty. We camera-inspect the line, hydro-jet the blockage, clear roots, and handle trenchless spot repairs so your yard doesn’t become a trench.",
      "bullets": [
        "In-line camera diagnosis",
        "High-pressure hydro-jetting",
        "Root intrusion removal",
        "Trenchless / spot line repair"
      ]
    },
    {
      "slug": "water-heaters",
      "title": "Water heaters & tankless",
      "short": "Same-day tank swaps and right-sized tankless conversions.",
      "body": "From a leaking 40-gallon tank to a full tankless conversion, we size the unit to your household so you never run cold mid-shower, and we haul the old one away.",
      "bullets": [
        "Same-day tank replacement",
        "Tankless conversions, sized right",
        "Gas & electric",
        "Old unit hauled away"
      ]
    },
    {
      "slug": "repipe-remodel",
      "title": "Repipe & remodel",
      "short": "Whole-home PEX & copper repipes, clean rough-in for remodels.",
      "body": "Rusty galvanized pipe or pinhole copper leaks? We repipe whole homes in PEX or copper with minimal drywall damage, and provide clean rough-in for kitchen and bath remodels.",
      "bullets": [
        "Whole-home PEX or copper",
        "Minimal-drywall methods",
        "Permit & inspection handled",
        "Kitchen & bath rough-in"
      ]
    },
    {
      "slug": "leak-detection",
      "title": "Leak detection",
      "short": "Acoustic & thermal location, find it without guessing.",
      "body": "A spiking water bill or warm spot on the floor usually means a hidden leak. Acoustic and thermal equipment pinpoints it so we open one spot, not your whole slab.",
      "bullets": [
        "Acoustic & thermal location",
        "Slab & under-ground leaks",
        "Pressure testing",
        "One precise repair, not exploratory demo"
      ]
    },
    {
      "slug": "fixtures",
      "title": "Faucets, fixtures & more",
      "short": "Faucets, toilets, disposals, hose bibs, softeners, pressure regulators.",
      "body": "The everyday list: faucets, toilets, garbage disposals, hose bibs, sump pumps, pressure regulators, and water-softener installs, tidy work with the old parts hauled away.",
      "bullets": [
        "Faucets, toilets, disposals",
        "Hose bibs & sump pumps",
        "Pressure regulators",
        "Water-softener installs"
      ]
    }
  ],
  "areas": [
    {
      "slug": "sacramento",
      "name": "Sacramento",
      "eta": "45-60 min",
      "neighborhoods": [
        "Midtown",
        "East Sacramento",
        "Land Park",
        "Curtis Park",
        "Pocket-Greenhaven",
        "Natomas"
      ],
      "blurb": "Our home base since 1992, from Midtown’s pre-war bungalows to Natomas new builds, we know the pipe."
    },
    {
      "slug": "roseville",
      "name": "Roseville",
      "eta": "50-70 min",
      "neighborhoods": [
        "West Roseville",
        "Fiddyment Farm",
        "Diamond Oaks",
        "Sun City"
      ],
      "blurb": "Fast coverage across Roseville and the 65 corridor, from Fiddyment new construction to Sun City retrofits."
    },
    {
      "slug": "folsom",
      "name": "Folsom",
      "eta": "55-75 min",
      "neighborhoods": [
        "Empire Ranch",
        "Briggs Ranch",
        "Historic Folsom",
        "Folsom Ranch"
      ],
      "blurb": "Folsom’s hard water is rough on water heaters and fixtures, we install and service for it daily."
    },
    {
      "slug": "elk-grove",
      "name": "Elk Grove",
      "eta": "55-75 min",
      "neighborhoods": [
        "Laguna",
        "Laguna West",
        "East Franklin",
        "Sheldon"
      ],
      "blurb": "Whole-home repipes and water-heater swaps across Elk Grove’s Laguna and Franklin neighborhoods."
    },
    {
      "slug": "davis",
      "name": "Davis",
      "eta": "60-80 min",
      "neighborhoods": [
        "Central Davis",
        "North Davis",
        "South Davis",
        "El Macero"
      ],
      "blurb": "Older Davis homes and student rentals alike, drain clearing, leak detection, and fixture work."
    },
    {
      "slug": "citrus-heights",
      "name": "Citrus Heights",
      "eta": "50-70 min",
      "neighborhoods": [
        "Sunrise",
        "Arcade Creek",
        "Birdcage",
        "Sylvan"
      ],
      "blurb": "Sewer-line and repipe specialists for Citrus Heights’ established Sunrise and Birdcage neighborhoods."
    }
  ],
  "financing": {
    "intro": "Big jobs, broken into monthly. Most repairs and installs qualify — $0 down, with a soft credit check that won’t affect your score.",
    "steps": [
      "Tell us about the job — repipe, water heater, sewer line, slab leak, or remodel.",
      "Apply in minutes with a soft credit check (no impact to your credit score).",
      "See your rate and options on the spot — $0 down to get started.",
      "Book the fix and pay over time on a plan that fits your budget."
    ],
    "qualifying": [
      "Repipes",
      "Water heaters",
      "Sewer lines",
      "Slab leaks",
      "Remodels",
      "Most repairs & installs"
    ],
    "fine": "Soft pull · no impact to your credit score."
  }
};
