#!/usr/bin/env node
/*
 * build.js — regenerate the portfolio gallery (index.html) and README.md from
 * the data files (categories.json + sites.json). Single source of truth = the
 * JSON. Run after any edit to the catalog:  node build.js
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const read = (f) => fs.readFileSync(path.join(HERE, f), 'utf8');
const readJSON = (f) => JSON.parse(read(f));

const cats = readJSON('categories.json');
const sites = readJSON('sites.json').map((s, i) => ({ ...s, idx: i + 1 }));
const BASE = 'http://localhost:8000';

// A site lives in its primary category `c` (name `n`) and may be cross-listed
// into other categories via `also: [{ c, n?, t? }]` — same href/idx, a
// category-specific display name. Placements never change the unique site
// count (sites.length stays the total); they only add extra cards/sections.
function placements(catKey) {
  const out = [];
  for (const s of sites) {
    const places = [{ c: s.c, n: s.n, t: s.t }].concat(
      (s.also || []).map((a) => ({ c: a.c, n: a.n || s.n, t: a.t || s.t }))
    );
    for (const p of places) {
      if (p.c === catKey) out.push({ ...s, n: p.n, t: p.t, _c: catKey });
    }
  }
  return out;
}

// ---- 1) Gallery (index.html) ---------------------------------------------
function buildGallery() {
  const tpl = read('gallery.template.html');
  const out = tpl
    .split('__CATS__').join(JSON.stringify(cats))
    .split('__SITES__').join(JSON.stringify(sites))
    .split('__COUNT__').join(String(sites.length));
  fs.writeFileSync(path.join(HERE, 'index.html'), out);
}

// ---- 2) README.md ---------------------------------------------------------
const BADGE_LABEL = { react: 'React (needs `npm run dev`)', wip: 'Work-in-progress', sketch: 'Design sketch', api: 'Live backend :8787' };

function buildReadme() {
  const L = [];
  L.push('# Website Portfolio — Full Index, Flow Charts & Localhost Links', '');
  L.push('Every website, app, background, and showcase across the entire `~/Documents` folder. For each: **brand name → flow chart → localhost link** you can paste straight into a browser.', '');
  L.push(`**${sites.length} distinct sites / experiments.** This file is generated from \`sites.json\` by \`build.js\` — run the **/Update_MyWebsitePortfolio** skill to add new sites.`, '');
  L.push('---', '');
  L.push('## 🎬 Visual showcase (recommended)', '');
  L.push('Open **http://localhost:8000/** — a live gallery of every site. Each card has an **Open ↗** button that launches the real project **in a new tab**, with search + category filters. Gallery file: [`index.html`](index.html).', '');
  L.push('The numbered index below is the same sites with their **flow charts**.', '');
  L.push('---', '');
  L.push('## ▶ How to open these', '');
  L.push('One static server, rooted at `~/Documents`:', '');
  L.push('```bash', 'python3 -m http.server 8000 --bind 127.0.0.1   # serves everything below', 'lsof -ti:8000 | xargs kill                       # stop it', '```', '');
  L.push('- **Hargrove** also runs its real backend at **http://localhost:8787** (working booking form).', '');
  L.push('- `%20` in a link = a folder with a space (`demo web`, `Mall CRM`) — keep it.', '');
  L.push('- **React/Vite** sites only show a dev shell as static — run `npm run dev` in their folder.', '');
  L.push('---', '');

  for (const cat of cats) {
    const items = placements(cat.key);
    if (!items.length) continue;
    L.push(`# ${cat.emoji || ''} ${cat.name}`.trim(), '');
    for (const s of items) {
      L.push(`## ${s.idx}. ${s.n}`);
      L.push(`**Type:** ${s.t}`);
      if (s.badge && s.badge.length) L.push(`**Notes:** ${s.badge.map((b) => BADGE_LABEL[b] || b).join(' · ')}`);
      L.push('**Flow chart:**');
      L.push('```', s.flow, '```');
      L.push(`**Localhost:** ${BASE}${s.href}`);
      for (const [lab, href] of (s.extras || [])) {
        const full = href.startsWith('http') ? href : BASE + href;
        L.push(`- ${lab} — ${full}`);
      }
      L.push('');
    }
    L.push('---', '');
  }

  L.push('## Summary by category', '');
  L.push('_Counts include cross-listed sites, so they sum to more than the total; the total is the unique-site count._', '');
  L.push('| Category | Cards |', '|---|---|');
  for (const cat of cats) {
    const n = placements(cat.key).length;
    if (n) L.push(`| ${cat.emoji || ''} ${cat.name} | ${n} |`);
  }
  L.push(`| **Total (unique sites)** | **${sites.length}** |`, '');
  L.push('_Generated by `build.js`. Edit `sites.json` or run `/Update_MyWebsitePortfolio`, never edit this file by hand._');

  fs.writeFileSync(path.join(HERE, 'README.md'), L.join('\n') + '\n');
}

buildGallery();
buildReadme();
console.log(`✅ built index.html + README.md from ${sites.length} sites across ${cats.length} categories.`);
